import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Navbar from "./Navbar";


export const metadata: Metadata = {
  title: "Resume Reviewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" data-webcrx="some-value">
      <body>
        <div >
          <div className="z-10 fixed inset-x-0 right-50 left-50">
            <Navbar/>
          </div>
          <div className="z-0 relative bg-cover text-white h-screen ">
            <div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
