import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./Navbar";


export const metadata: Metadata = {
  title: "Resume Reviewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" webcrx="">
      <body>
        <div>
        <div className="z-10  absolute right-50 left-50">
          <Navbar/>
        </div>
        <div className="z-0 relative text-white bg-black h-screen">
          {children}
       
        </div>
        </div>
      </body>
    </html>
  );
}
